"""Add color and price columns

Revision ID: cfd67cc3ad02
Revises: 16f44ca1e1ae
Create Date: 2024-04-28 11:50:53.515953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfd67cc3ad02'
down_revision = '16f44ca1e1ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('price', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_column('price')
        batch_op.drop_column('color')

    # ### end Alembic commands ###
